version: "2"
services:
  mysql:
    container_name: mp-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nonoob
    ports:
      - "3306:3306"
    networks:
        - mp-network
  redis:
    image: redis:3-alpine
    container_name: mp-redis
    ports:
      - "6379:6379" 
    networks:
        - mp-network   
  php:
    image: pedrotti/laravel
    container_name: mp-php
    working_dir: /var/www/html 
    volumes:
      - .:/var/www/html
    links:
      - mysql:db
      - redis:cache
    ports:
      - "80:80"
    networks:
        - mp-network
networks:
  mp-network:
    driver: bridge
