version: "2"
services:
  mysql:
    container_name: nonoob-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nonoob
    ports:
      - "3306:3306"
    networks:
        - nonoob-network
  redis:
    image: redis:3-alpine
    container_name: nonoob-redis
    ports:
      - "6379:6379" 
    networks:
        - nonoob-network   
  php:
    image: pedrotti/laravel
    container_name: nonoob-php
    volumes:
      - .:/var/www/html
    links:
      - mysql:db
      - redis:cache
    ports:
      - "80:80"
    networks:
        - nonoob-network
networks:
  nonoob-network:
    driver: bridge
